feat: add context object to log messages
zwave-js/node-zwave-js pull request #3251
Opened 2021-08-27 15:15 UTC by raman325

I'm not sure that everything I've captured is strictly necessary so we can relax some of this based on feedback

2021-08-28 14:20 UTC, AlCalzone requested changes
I'm wondering if `context` should have a `type` property or something that can be used to distinguish between several possible contexts an application might encounter.

Also, for type safety, we should probably define the different specific context types and export them.

2021-08-28 14:20 UTC, AlCalzone commented on packages/zwave-js/src/lib/log/Driver.ts
> +			context: CONTEXT,
```suggestion
			context: { ...CONTEXT },
```
would avoid a situation where applications can change our `CONTEXT` object's contents.

2021-08-28 14:20 UTC, AlCalzone commented on packages/zwave-js/src/lib/log/Driver.ts
> +			context: CONTEXT,
dito

2021-09-01 15:25 UTC, raman325 commented
> I'm wondering if `context` should have a `type` property or something that can be used to distinguish between several possible contexts an application might encounter.
> 
> Also, for type safety, we should probably define the different specific context types and export them.

That's `source` the way I have currently implemented it, but we can switch to `type` since you use that elsewhere. And stronger typing is a good idea

2021-09-01 16:56 UTC, raman325 commented
@AlCalzone when you say you want to type the different context types, do you mean for example typing https://github.com/zwave-js/node-zwave-js/pull/3251/files#diff-7076042951692d76ef597b7bae4634cb8110f9a95eb8708065fdf41cd0a4c919R98-R103 and https://github.com/zwave-js/node-zwave-js/pull/3251/files#diff-7076042951692d76ef597b7bae4634cb8110f9a95eb8708065fdf41cd0a4c919R144-R151 as distinct types?

2021-09-01 19:18 UTC, AlCalzone commented
> That's `source` the way I have currently implemented it

Yes, but it doesn't distinguish between the possible contexts, e.g. there are multiple `source: "controller"` contexts.


> @AlCalzone when you say you want to type the different context types, do you mean for example typing [#3251 (files)](https://github.com/zwave-js/node-zwave-js/pull/3251/files#diff-7076042951692d76ef597b7bae4634cb8110f9a95eb8708065fdf41cd0a4c919R98-R103) and [#3251 (files)](https://github.com/zwave-js/node-zwave-js/pull/3251/files#diff-7076042951692d76ef597b7bae4634cb8110f9a95eb8708065fdf41cd0a4c919R144-R151) as distinct types?

Yep

2021-09-07 21:09 UTC, raman325 commented
@zwave-js-bot fix lint

2021-09-07 21:20 UTC, raman325 commented
@zwave-js-bot fix lint

2021-09-18 19:37 UTC, AlCalzone commented
@raman325 let me know when you're done here :)

2021-09-18 22:14 UTC, raman325 commented
I'm done, this is ready for review!

2021-10-15 07:11 UTC, AlCalzone commented
Sorry it took me so long. I've made a few changes:
* exported all log context types
* converted some of the types to generics to let TypeScript validate the contexts better
* made the `type` property to distinguish logs from the same logger optional
* removed the limitation of `source`, so applications which hook into the logging functionality (like Node Red) can still do it.

2021-10-15 07:12 UTC, AlCalzone approved these changes
OK with my changes - @raman325 can you give this another test?

2021-10-17 07:29 UTC, raman325 commented
> OK with my changes - @raman325 can you give this another test?

I will test this in the next day or two and get back to you

2021-10-19 06:01 UTC, AlCalzone commented
Huh?

2021-10-19 14:28 UTC, raman325 commented
uhh this was not intentional. Shit

2021-10-19 20:49 UTC, raman325 commented
sorry for the delay @AlCalzone but I tested the changes and everything looks good! I think we are OK to merge

2021-10-19 21:16 UTC, merged