feat(config): add support for HE-FT01, small fixes for HE-HT01
zwave-js/node-zwave-js pull request #3607
Opened 2021-10-27 20:11 UTC by popescunsergiu

feat(config): add support for he-ft01
fix(config): small fixes for he-ht01

2021-10-27 21:07 UTC, AlCalzone requested changes
I think you mixed up the filenames. Otherwise mostly looks good.

2021-10-27 21:07 UTC, AlCalzone commented on packages/config/config/devices/0x0344/he-ht01.json
> +			"label": "Fan Medium Speed Relay Load Power",
I don't understand this label.

2021-10-27 21:07 UTC, AlCalzone commented on packages/config/config/devices/0x0344/he-ht01.json
> +			"label": "Fan High Speed Relay Load Power",
dito

2021-10-27 21:07 UTC, AlCalzone commented on packages/config/config/devices/0x0344/he-ht01.json
> +			"label": "Heating Valve Relay Load Power",
dito

2021-10-27 21:07 UTC, AlCalzone commented on packages/config/config/devices/0x0344/he-ht01.json
> +			"label": "Cooling Valve Relay Load Power",
dito

2021-10-28 10:48 UTC, popescunsergiu commented on packages/config/config/devices/0x0344/he-ht01.json
> +			"label": "Fan Medium Speed Relay Load Power",
This was my mistake. I've worked on FT01 and fixed some HT01 params but I've reversed the file names in the process

I also added description to the params

2021-10-28 10:48 UTC, popescunsergiu commented on packages/config/config/devices/0x0344/he-ht01.json
> +			"label": "Fan High Speed Relay Load Power",
Same as above

2021-10-28 10:48 UTC, popescunsergiu commented on packages/config/config/devices/0x0344/he-ht01.json
> +			"label": "Heating Valve Relay Load Power",
Same as above

2021-10-28 10:48 UTC, popescunsergiu commented on packages/config/config/devices/0x0344/he-ht01.json
> +			"label": "Cooling Valve Relay Load Power",
Same as above

2021-10-28 10:52 UTC, popescunsergiu commented
> I think you mixed up the filenames. Otherwise mostly looks good.

Fixed it, sorry for the issue

2021-10-28 14:49 UTC, AlCalzone approved these changes
I've reworked the description again. After reading the part in the manual twice, it made more sense :D

2021-10-28 14:53 UTC, merged